server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html/public;

    add_header X-Debug-Request-URI $request_uri always;
    add_header X-Debug-Request-Filename $request_filename always;

    location = / {
        index index.html;
        try_files /index.html =404;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
